### Configure the main teb code here.
## Read the guidance at the bottom of this file before use.

## Target and file names
name: ASAS_J051753-5406.0     # Target name; must be resolvable by SIMBAD
run_id: nominal               # Prefix used in output save file

## Physical properties of the binary stars
teff1: 6500                   # Best estimate of T_eff,1, in Kelvin
teff2: 6350                   # Best estimate of T_eff,2, in Kelvin
logg1: 3.9834                 # Surface gravity for primary star, in cgs.
logg2: 4.3306                 # Surface gravity for secondary star, in cgs.
m_h: 0.02                     # Metallicity for both stars.
aFe: 0.0                      # Alpha fraction for both stars.
r1:                           # Primary star radius and error, in solar units
  - 1.9299
  - 0.0024
r2:                           # Secondary star radius and error, in solar units
  - 1.1809
  - 0.0015
plx:                          # Gaia EDR3 parallax and error, in mas
  - 2.6256
  - 0.014
ebv:                          # Prior on interstellar E(B-V) and error
  - 0.0020
  - 0.0006

## Configuration parameters for the teb method
# Model SED source and distortion
model_sed: bt-settl           # Model SEDs to use [bt-settl, bt-settl-cifist, coelho-sed]
binning: 50                   # Wavelength resolution of model SED, in Angstrom
distortion: 2                 # Type of distortion to use:
                              # 0 = no distortion applied (simple SED fit)
                              # 1 = single distortion function for both (not recommended)
                              # 2 = each star's SED distorted separately (recommended)
n_coeffs: 3                   # Number of distortion coefficients to use.
# Priors and data to include
apply_ebv_prior: True         # Put a prior on E(B-V)? Uses provided value and error.
apply_fratio_prior: True      # Calculate and apply priors on flux ratios in the near-IR?
apply_k_prior: False          # Put a prior on the radius ratio (total eclipses only)
apply_colors: False           # Include any colors data in photometry_data.yaml?
sigma_ext: 0.008              # Prior on external noise on magnitude data
sigma_l: 0.01                 # Prior on external noise on flux ratios
sigma_c: 0.005                # Prior on external noise on colors
# MCMC and display options
mcmc_n_steps: 2000            # Number of steps to use in MCMC simulations
mcmc_n_walkers: 256           # Number of walkers to use in MCMC simulations
show_plots: True              # Generate convergence, corner and final SED plots?
save_plots: True              # Whether to save these plots in output directory
corner_exclude_coeffs: False  # Whether to exclude distortion coeffs from being displayed
                              # in corner plot (recommended for large 'n_coeffs')


### HOW TO USE THIS CONFIGURATION FILE

## A note on the stellar radii
# If you have very precise measurements for radii (0.2% or better), these should technically be the Rosseland radii

## A note on the distortion type
# Using a single set of distortion coefficients will reduce the Bayesian Information Criterion on the fit BUT
# will fix the flux ratio at a constant value for all wavelengths. For a better approach use 2.

## A note on the model SEDs
# BT-Settl, BT-Settl-CIFIST and to a lesser extent, Coelho SED models are supported by teb
# teb can integrate between T_eff, log(g) and [M/H] if given value != existing model SED
# N.B. not all T_eff-log(g) combinations are supported by all model catalogs.
# * BT-Settl: Asplund et al. (2009) solar abundances. M/H = [0.5, 0.3, 0.0, -0.5, -1.0, ..., -4.0]
# http://svo2.cab.inta-csic.es/theory/newov2/index.php?models=bt-settl
# * BT-Settl-CIFIST: Caffau et al. (2011) solar abundances, only [M/H] = 0. teb will overwrite [M/H] if != 0.
# http://svo2.cab.inta-csic.es/theory/newov2/index.php?models=bt-settl-cifist
# * Coelho SED: limited range 130nm - 10um, sparse teff-logg, M/H = [0.2, 0.0, -0.1, -0.3, -0.5, -0.8, -1.0, -1.3]
# http://svo2.cab.inta-csic.es/theory/newov2/index.php?models=coelho_sed
# Using these SEDs may give spurious results due to the limited wavelength range
