### Core parameters to configure the temperature method.
name: ASAS_J051753-5406.0  # Target name; must be resolvable by SIMBAD
run_id: test  # Prefix used in output save file

# Configure the method
distortion: 1             # 0 = no distortion applied, 1 = single distortion function for both stars,
                          # 2 = each star's SED distorted separately.
n_coeffs: 10              # Number of distortion coefficients to use. Use 0 for a simple SED fit.
apply_ebv_prior: True     # Whether to apply the E(B-V) prior specified below
apply_fratio_prior: True  # Whether to apply the NIR flux ratio priors
apply_colors: False       # Whether to include colors data
sigma_ext: 0.008          # External noise
sigma_l: 0.01             # Flux ratios
sigma_c: 0.005            # Colors

# MCMC and display options
mcmc_n_steps: 1000            # Number of steps to use in MCMC simulations
mcmc_n_walkers: 256           # Number of walkers to use in MCMC simulations
show_plots: True              # Whether to generate convergence, corner and final SED plots
corner_exclude_coeffs: False  # Whether to exclude distortion coeffs from being displayed in corner plot
                              # (recommended for large values of 'n_coeffs')

# Physical parameters of the two stars
teff1: 6410   # Best value of T_eff,1, in Kelvin
teff2: 6270   # Best value of T_eff,2, in Kelvin
plx:
  - 2.6256    # Gaia EDR3 parallax and error, in milliarcseconds
  - 0.014
r1:
  - 1.935     # Primary radius and error, in solar units
  - 0.020
r2:
  - 1.181     # Secondary radius and error, in solar units
  - 0.014
ebv:
  - 0.00269   # Prior on interstellar E(B-V) and error
  - 0.00119

# Starting values of stellar models to use as basis for integrating function
# NB: not all teff-logg combinations supported by all model catalogs. Check URL for full coverage info.
# BT-Settl: full wavelength range, detailed logg-teff coverage BUT only supports M/H = 0
# http://svo2.cab.inta-csic.es/theory/newov2/index.php?models=bt-settl
# Coelho SED: limited wavelength range 130nm - 100micron and sparser teff-logg coverage.
# http://svo2.cab.inta-csic.es/theory/newov2/index.php?models=coelho_sed
model_sed: coelho-sed     # Which model SEDs to use. Libraries supported: bt-settl, coelho-sed
binning: 50   # Wavelength resolution to use, in Angstroms.
# The code will use teff1, teff2 and interpolate the models.
logg1: 4.0    # Surface gravity for primary star, in cgs. Only increments of 0.5 currently supported.
logg2: 4.0    # Surface gravity for secondary star, in cgs. Only increments of 0.5 currently supported.
# If model_sed == bt-settl, if these != 0 they will be automatically overwritten as 0
m_h: -0.1     # Metallicity for both stars. (C) supports [0.2, 0.0, -0.1, -0.3, -0.5, -0.8, -1.0, -1.3]
aFe: 0.4      # Alpha fraction for both stars. (C) supports [0.0, 0.4]
