### Adjust your parameters for the flux ratio prior calculations here.
# The size of search range should reflect the uncertainty on the parameter plus a little
# extra, e.g. at least twice the error bar. If unsure about whether to use lin or quad,
# check by plotting V-K colour against catalog temperature.
#TODO: Include option to restrict metallicity.
#TODO: Include option for single fit for stars with similar parameters.
#
# Linear (lin) or quadratic (quad) fit to the V-K vs. Teff diagram
method: quad
# Flux ratio of the binary, flux2/flux1
flux_ratio: 1.03
# Nominal temperature for the primary & secondary stars to use in initial flux ratio prior calculation
teff1: 6300
teff2: 6100
# Range of interstellar reddening to restrict reference star search by
E(B-V):
  - -1.0
  - 0.01
# Range of surface gravities to restrict reference star search
logg1:
  - 3.5
  - 4.5
logg2:
  - 3.8
  - 4.8
# Range of temperatures to restrict reference star search by
tref1:
  - 5400
  - 6600
tref2:
  - 5300
  - 6500
