### Include your photometric data values here.
# Currently supported: Johnson UBVRI, Stromgren uvby, Skymapper uvgriz, TESS, Galex, 2MASS, WISE, Gaia EDR3
flux_ratios:
  - tag: TESS
    type: TESS
    value:
      - 0.3 # dummy numbers
      - 0.01

# Photometry NOT from Galex, Gaia, 2MASS or WISE.
extra_data:
  - tag: u
    type: skymapper_u
    mag:
      - 11.7698
      - 0.0091
    zp:
      - -48.346
      - 0.216
    file: Response/SkyMapper_SkyMapper.u.dat  # Must be ascii. 2 columns: wave (in ngstrom) & response (normalised).
  - tag: v
    type: skymapper_v
    mag:
      - 11.3121
      - 0.0105
    zp:
      - -48.51
      - 0.024
    file: Response/SkyMapper_SkyMapper.v.dat  # Must be ascii. 2 columns: wave (in ngstrom) & response (normalised).
# Colours. Stromgren b-y, m1, c1, and Gaia BP-RP currently supported.
colors_data:
  - tag: BP-RP
    type: BPRP
    color:
      - 0.61822796
      - 0.01498220